### ISSUE TITLE
Source please?

### ISSUE THREAD

**Issue by fluffynuts** [GeoSaffer/ToAffinityAndBeyond#5]
Putting a project up on GitHub without source is ... odd.

Please opensource or select to create a product site somewhere.

**Comment by GeoSaffer** [comment]
no

**Comment by fluffynuts** [comment]
🤡 

I'll consider the releases from this repo to be malware then, as they're doing low-level work and not showing how - could be doing anything.

**Comment by GeoSaffer** [comment]
Seems like the biggest issue you have is **"not showing how"**. Don't be lazy, do your own research.

This project was created to be helpfull to some communities, and just because you are not getting your way does not make it malware. Any dev worth his salt should be able to decompile and inspect the actions of this program.

I have my reasons to not share the code, you have just added another reason to the list.

It's good practice to consider all pieces of compiled code as malicious, and to proceed with caution.

**Comment by fluffynuts** [comment]
indeed, as I am considering this repo malicious and will warn others to do so too (: have a great day.
